myapp/views/matches.py
import random

from flask import Blueprint, render_template, request, url_for, redirect, jsonify, abort
from ..models import db, User, UserInterests, UserProfile, NotInterested, Conversation, Message, Notification
from myapp import g
from ..socket_init import socketio
from flask_socketio import emit, SocketIO, join_room, leave_room
from ..helpers import apology

matches_bp = Blueprint("matches", __name__)

@matches_bp.route("/matches", methods=["GET", "POST"])
def matches():
    profile = g.user_profile

    if profile is None:
        return apology("None")

    #**Select all users for now
    if request.method == "POST":
        action = request.form.get("action")

        # INTERESTED
        if action == "interested":
            liked_id = request.form.get("user_id")
            notification = request.form.get("notification")
            print("You like: ", liked_id)

            # Check if user is already in NotInterested
            existing_not_interested = NotInterested.query.filter_by(user_id=g.user_profile.id, target_id=liked_id).first()
            if existing_not_interested:
                db.session.delete(existing_not_interested)
                db.session.commit()

            try:
                # Add interest
                new_interest = UserInterests(user_id=g.user_profile.id, liked_user_id=liked_id)
                db.session.add(new_interest)
                # Send user notification
                new_notification = Notification(sender_id=g.user_profile.id, recipient_id=liked_id, notification_type=notification)
                db.session.add(new_notification)
                db.session.commit()

                # Find selected user 
                selected_user = UserProfile.query.filter(UserProfile.user_id == liked_id).first()

                if selected_user:
                    user_data = {"userid": selected_user.user_id, 
                                 "fullname": selected_user.full_name, 
                                "picture": selected_user.picture, 
                                "age": selected_user.age, 
                                "city": selected_user.city, 
                                "state": selected_user.state,
                                "school": selected_user.school, 
                                "company": selected_user.company
                                
                                }

                # return json data to display the add to left panel (matches)
                return jsonify(user_data)
                
            except Exception as e:
                print("Error inserting interests:", str(e))
                return apology("Error inserting interest")
        
        # If user is not interested
        elif action == "not-interested":
            disliked_id = request.form.get("user_id")
            print("Not Interested: ", disliked_id)
            # look for interest user in interested
            existing_interest = UserInterests.query.filter_by(user_id=g.user_profile.id, liked_user_id=disliked_id).first()
            if existing_interest:
                db.session.delete(existing_interest)
                db.session.commit()
        
            try:
                # Add non-interest to not interested table
                not_interested = NotInterested(user_id=g.user_profile.id, target_id=disliked_id)
                db.session.add(not_interested)
                db.session.commit()
                return "Success"
            except Exception as e:
                print("Error marking as not interested:", str(e))
                return apology("Error marking as not interested")

        # show selected user's profile when clicked
        elif action == "display-user":
            selected_id = request.form.get("selectedUser")

            likeBackIsTrue = False

            # check if the selected user has liked back
            selected_like_back = UserInterests.query.filter(UserInterests.user_id == selected_id, UserInterests.liked_user_id == profile.id).first()
            print("selected like back: ", selected_like_back)

            if selected_like_back:
                likeBackIsTrue = True
            
            if selected_id:
                print("selected id: ", selected_id)

                # Find selected profile to display on the right panel
                selected_user = UserProfile.query.filter_by(user_id=selected_id).first()

                print("like back: ", likeBackIsTrue)

                if selected_user:

                    user_data = {"userid": selected_user.user_id, 
                                 "fullname": selected_user.full_name, 
                                "picture": selected_user.picture, 
                                "age": selected_user.age, 
                                "city": selected_user.city, 
                                "state": selected_user.state,
                                "school": selected_user.school, 
                                "company": selected_user.company,
                                "likeBack": likeBackIsTrue
                                }
                    
                    # return json data of selected user to display
                    return jsonify(user_data)
                
                else:
                    abort(404)

            else:
                return jsonify({"error": "No selected user id"})

        elif action == "show-sender-notification":
            sender_id = request.form.get("senderId")

            sender_profile = UserProfile.query.filter_by(user_id=sender_id).first()

            if sender_profile:

                user_data = {
                    "userid": sender_id,
                    "name": sender_profile.full_name,
                    "age": sender_profile.age,
                    "city": sender_profile.city,
                    "state": sender_profile.state
                }

            return jsonify(user_data)

    else:
        # Get a random profile to display
        random_user = get_random_user(profile)
        print(random_user)

        # Other users' profile
        interested_profiles = get_interested_profiles(profile)

        # User's notifications
        notifications = Notification.query.filter(Notification.recipient_id == g.user_profile.id).all()

        #check if both users are interested in each other

        return render_template("matches.html", profile=profile, match=random_user,
                                interests=interested_profiles, notification=notifications)

def get_random_user(profile):
    interests_ids = [record.liked_user_id for record in UserInterests.query.filter_by(user_id=g.user_profile.id).all()]
    not_interested_ids = [record.target_id for record in NotInterested.query.filter_by(user_id=g.user_profile.id).all()]

    users_query = UserProfile.query.filter(UserProfile.user_id != profile.id)

    if profile.sexuality == "heterosexual":
        users_query = users_query.filter(UserProfile.gender != profile.gender)
    elif profile.sexuality == "homosexual":
        users_query = users_query.filter(UserProfile.gender == profile.gender)

    users_profile = users_query.filter(
        ~UserProfile.user_id.in_(interests_ids) & ~UserProfile.user_id.in_(not_interested_ids)
    ).all()

    if not users_profile:
        abort(404)
    
    random_profile = random.choice(users_profile)
    return {"userid": random_profile.user_id, 
        "fullname": random_profile.full_name, 
        "picture": random_profile.picture, 
        "age": random_profile.age, 
        "city": random_profile.city, 
        "state": random_profile.state,
        "school": random_profile.school, 
        "company": random_profile.company

    }

@matches_bp.route("/matches/next-user", methods=["GET"])
def get_next_user():

    current_user_id = request.args.get("currentUserId")

    current_user_profile = UserProfile.query.filter_by(user_id=current_user_id).first()

    if current_user_profile.sexuality == "heterosexual":
        users_profile = UserProfile.query.filter((UserProfile.user_id != current_user_id) & (UserProfile.gender != current_user_profile.gender))
    elif current_user_profile.sexuality == "homosexual":
        users_profile = UserProfile.query.filter((UserProfile.user_id != current_user_id) & (UserProfile.gender == current_user_profile.gender))
    else:
        users_profile = UserProfile.query.filter(UserProfile.user_id != current_user_id)

    interests_ids = [record.liked_user_id for record in UserInterests.query.filter_by(user_id=current_user_id).all()]
    not_interested_ids = [record.target_id for record in NotInterested.query.filter_by(user_id=current_user_id).all()]

    users_profile = users_profile.filter(~UserProfile.user_id.in_(interests_ids) & ~UserProfile.user_id.in_(not_interested_ids))

    if not users_profile:
        abort(404)
    
    users_profile_list = list(users_profile)

    random_profile = random.choice(users_profile_list)

    print("Random profile: ", random_profile)

    if random_profile:
        random_user_data = { "userid": random_profile.user_id,
                            "fullname": random_profile.full_name,
                            "picture": random_profile.picture,
                            "age": random_profile.age,
                            "city": random_profile.city,
                            "state": random_profile.state,
                            "school": random_profile.school,
                            "company": random_profile.company
                            }
        return jsonify(random_user_data)
    else:
        return jsonify({"error": "No random user found"})
            
def get_interested_profiles(profile):
    return UserProfile.query.join(UserInterests, UserProfile.user_id == UserInterests.liked_user_id).filter(
        UserInterests.user_id == profile.id
    ).all()

    
# SocketIO notification event handler
@socketio.on("notification")

myapp/views/messages.py
# MESSAGES
from flask import Blueprint, render_template, request, redirect, jsonify
from myapp import g
from flask_socketio import emit, join_room, leave_room
from ..models import Conversation, Message, UserProfile, db
from ..helpers import apology
from ..socket_init import socketio

message_bp = Blueprint("messages", __name__)

@message_bp.route("/messages", methods=["GET", "POST"])
def messages():
    profile = g.user_profile

    if request.method == "POST":

        action = request.form.get("action")

        # Send message
        if action == "send-message":
            chatUserId = request.form.get("chatUserId")

            message = request.form.get("content")

            new_message = Message(sender_id=profile.id, recipient_id=chatUserId, content=message)
            db.session.add(new_message)
            db.session.commit()

            all_messages = Message.query.filter((Message.sender_id == profile.id) & (Message.recipient_id == chatUserId)).order_by(Message.timestamp).all()


            user_profile = UserProfile.query.filter_by(user_id=g.user_profile.id).first()
            recipient_profile = UserProfile.query.filter_by(user_id=chatUserId).first()
            print("recipient_profile", recipient_profile)

            message_content = {
                "sender": profile.id,
                "recipient": chatUserId,
                "content": message,
                "senderPic": user_profile.picture,
                "recipientPic": recipient_profile.picture
            }

            return jsonify(message_content)
        
        # Show selected user's conversation
        elif action == "display-conversation":
            selected_user = request.form.get("selectedUser")
            print("selecteduser: ", selected_user)

            selected_user_profile = UserProfile.query.filter_by(user_id=selected_user).first()

            userData = selected_user_profile.serializeUserProfile()

            messages = Message.query.filter((
                Message.sender_id == selected_user) & (Message.recipient_id == profile.id) | 
                (Message.recipient_id == selected_user) & (Message.sender_id == profile.id)).all()

            messageData = [message.serializeMessage() for message in messages]

            selected_user_data = {
                "selectedUserProfile": userData,
                "allMessages": messageData
            }

            return jsonify(selected_user_data)

    else:
        
        all_messages = Message.query.filter((Message.sender_id == profile.id) | (Message.recipient_id == profile.id)).all()

        participant_ids = set()        
        for message in all_messages:
            participant_ids.add(message.sender_id)
            participant_ids.add(message.recipient_id)

        participants = UserProfile.query.filter(UserProfile.id.in_(participant_ids) & (UserProfile.user_id != g.user_profile.id)).all()
   
        return render_template("messages.html", profile=profile, participants=participants)
  
@message_bp.route("/get-user", methods=["GET"])
def get_user():

    chatId = request.args.get("sender")

    chat_profile = UserProfile.query.filter_by(user_id=chatId).first()

    user_data = chat_profile.serializeUserProfile()

    chat_messages = Message.query.filter_by(recipient_id=chatId).all()
   
    messageData = [message.serializeMessage() for message in chat_messages]

    chat_data = {
        "userData": user_data,
        "messageData": messageData
    }

    return jsonify(chat_data)


# SocketIO event handler
# Listens for messages
@socketio.on("message")
def handle_message(data):
    senderId = data["senderId"]
    recipientId = data["recipientId"]
    message = data["message"]
    senderPic = data["senderPic"]
    recipientPic = data["recipientPic"]

    join_room(recipientId)

    print(f"Received {message} from {senderId} on server")
    emit("message", {"senderId": senderId, "recipientId": recipientId, "message": message, "senderPic": senderPic, "recipientPic": recipientPic, "room": recipientId}, room=recipientId)

# Listens for who joins the room
@socketio.on('join_room')
def handle_join_room(data):
    room = data['room']
    join_room(room)

myapp/views/profile.py
from flask import Blueprint, render_template, request
from ..models import User, UserProfile, UserInterests, NotInterested, db
from myapp import g
from flask import Blueprint, render_template

profile_bp = Blueprint("profile", __name__)

# PROFILE
@profile_bp.route("/profile")
def profile():
    profile = g.user_profile
    
    return render_template("profile.html", profile=profile)

# UPDATE PROFILE
@profile_bp.route("/update_profile", methods=["POST"])
def update_profile():

    user_profile = UserProfile.query.filter_by(user_id=g.user_profile.id).first()

    print(user_profile)

    # Get the new information from the request
    new_bio = request.form.get("bioVal")
    new_name = request.form.get("nameVal")
    new_age = request.form.get("ageVal")
    new_city = request.form.get("cityVal")
    new_state = request.form.get("stateVal")
    new_school = request.form.get("schoolVal")
    new_company = request.form.get("companyVal")
    new_gender = request.form.get("genderVal")
    new_sex = request.form.get("sexVal")

    if user_profile:
        # Update existing profile with new data
        if new_bio:
            user_profile.bio = new_bio
        if new_name:
            user_profile.name = new_name
        if new_age:
            user_profile.age = new_age
        if new_city:
            user_profile.city = new_city
        if new_state:
            user_profile.state = new_state
        if new_school:
            user_profile.school = new_school
        if new_company:
            user_profile.company = new_company
        if new_gender:
            user_profile.gender = new_gender
        if new_sex:
            user_profile.sex = new_sex

        db.session.commit()
        
        return "Profile data updated successfully"
    else:
        return "User profile not found"

myapp/templates/apology.html
{% extends "layout.html" %}

{% block title %}
    Apology
{% endblock %}

{% block main %}
    <!-- https://memegen.link/ -->
    <img alt="{{ top }}" class="border img-fluid" src="https://memegen.link/custom/{{ top | urlencode }}/{{ bottom | urlencode }}.jpg?alt=https://i.imgur.com/CsCgN7Ll.png&width=400" title="{{ top }}">
{% endblock %}

myapp/templates/index.html
{% extends 'layout.html' %}

{% block title %}
    Index
{% endblock %}

{% block main %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-3">
                <div class="user-panel" data-userid="{{ profile.id }}">
                    <div class="panel-header">
                        {% if profile.picture %}
                            <a href="/profile"><img src="{{ profile.picture }}" alt="user-profile-pic" class="user-profile-pic"></a>
                        {% else %}
                            <a href="/profile"><img src="../static/pictures/default-profilepic.jpg" alt="user-profile-pic" class="user-profile-pic"></a>
                        {% endif %}
                        <div class="panel-header-info">
                            <h5>{{ profile.full_name }}</h5>
                            <div class="dropdown">
                                <i class="fa-solid fa-gear fa-lg" style="color: #ffffff;" type="button" data-bs-toggle="dropdown" aria-expanded="false"></i>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="/logout">Logout</a></li>
                                </ul>
                            </div>
                            <!-- Notification toggle-->
                            <a class="fetch-notifications" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
                                <i class="fa-solid fa-bell fa-lg" style="color: #ffffff;"></i>
                            </a>
                        </div>
                    </div>
                    <!-- Bootstrap offcanvas -->
                    <!-- Notification content -->
                    <div class="dropdown">
                        <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
                          <div class="offcanvas-header">
                            <h5 class="offcanvas-title" id="offcanvasExampleLabel">Notification</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                          </div>
                          <div class="offcanvas-body">
                              <ul class="notification-list">
                                <!-- Javscript append elements here -->
                              </ul>
                          </div>
                        </div>
                      </div>
                  </div>
                <div class="user-panel-body">
                    <nav class="navbar navbar-expand-md matches" id="matches-navbar">
                        <div class="container-fluid" id="panel-nav">
                            <ul class="navbar-nav me-auto mt-2">
                                <li>
                                    <a id="match-nav" class="nav-link {% if request.path == url_for('matches.matches') %}active{% endif %}" href="{{ url_for('matches.matches') }}">Matches</a>
                                </li>
                                <li>
                                    <a id="message-nav" class="nav-link {% if request.path == url_for('messages.messages') %}active{% endif %}" href="{{ url_for('messages.messages') }}">Messages</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                    <div class="upb-content">
                        <!-- Notification Modal -->
                        <div class="modal fade" id="notificationModal" tabindex="-1" aria-labelledby="notificationModal" aria-hidden="true">
                            <div class="modal-dialog notificationDialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="notificationModalModalLabel">Notification</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body notification">
                                        <p>You've received a like.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% block panel %}{% endblock %}
                    </div>
                </div>
            </div>
            <div class="col-9">
                <div class="display-panel">
                    {% block display %}{% endblock %}
                </div>               
            </div>
        </div>
    </div>
    
{% endblock %}

myapp/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HeartSync</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/style/style.css" >
    <link rel="stylesheet" href="/static/style/mqueries.css">
    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/f6a29f035f.js" crossorigin="anonymous"></script>
    <!-- <link rel="icon" href="../icons/heart-beat.png" type="image/png"> -->
</head>
<body>
    <!-- NAVBAR -->
    {% if not session["user_id"] %}
        <nav class="navbar navbar-expand-md">
            <div class="container-fluid">
                <a class="navbar-brand" href="/"><i class="fa-solid fa-heart-pulse" style="color: #ff2e2e;"></i>  HeartSync</span></a>
                <button aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-bs-target="#navbar" data-bs-toggle="collapse" type="button">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbar">
                    {% if session["user_id"] %}
                        <ul class="navbar-nav ms-auto mt-2">
                            <li class="nav-item"><a class="nav-link" href="/account">Account</a></li>
                            <li class="nav-item"><a class="nav-link" href="/logout">Log Out</a></li>
                        </ul>
                    {% else %}
                        <ul class="navbar-nav ms-auto mt-2">
                            <li class="nav-item"><a class="nav-link" href="/register">Register</a></li>
                            <li class="nav-item"><a class="nav-link" href="/login">Log In</a></li>
                        </ul>
                    {% endif %}
                </div>
            </div>
        </nav>
    {% endif %}
        <!-- Content -->
        {% block main %}{% endblock %}
        <footer class="footer">
            <i class="fa-light fa-x" style="cursor: pointer; padding-bottom: 40px; float: right;" id="closeFooter" onclick="closeFooter()"></i>
            <p>Using Bootstrap</p>
            <p>Icons by FontAwesome</p>
            <p>Notification sounds by Pixabay</p>
            <p>The people's photos used for this project are AI generated. Website: https://this-person-does-not-exist.com/en</p>
            <p id="disclaimer">Disclaimer: Photo Ownership</p>
            <p>The photos used in this project are for illustrative purposes only. The ownership and copyright of these photos belong to their respective creators 
                and copyright holders. The use of these photos in this project does not imply ownership or endorsement. If you are the copyright owner of any of the 
                photos used and would like them to be removed or credited differently, please contact us, and we will promptly address your concerns.
                This project respects the intellectual property rights of others, and every effort has been made to comply with copyright laws and give proper attribution where applicable.</p>
        </footer>  
        <!-- SocketIO -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"></script>

        <!--Bootstrap JavaScript -->
        <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
        
        <!-- Google API -->
        <script src="https://apis.google.com/js/api.js"></script>

        <!-- Project Stylesheets -->
        <script src="/static/scripts/index.js"></script>
        <script src="/static/scripts/message.js"></script>
        <script src="/static/scripts/notification.js"></script>
        <script src="/static/scripts/profile.js"></script>
</html>

myapp/templates/login.html
{% extends "layout.html" %}

{% block title %}
    Log In
{% endblock %}

{% block main %}
    <form action="/login" method="post" id="loginForm">
        <div class="mb-3">
            <input autocomplete="off" autofocus class="form-control mx-auto w-auto" id="username" name="username" placeholder="Username" type="text">
        </div>
        <div class="mb-3">
            <input class="form-control mx-auto w-auto" id="password" name="password" placeholder="Password" type="password">
        </div>
        <button class="btn btn-primary" type="submit">Log In</button>
    </form>    
    
{% endblock %}

myapp/templates/matches.html
{% extends "index.html" %}

{% block title %}
    Matches
{% endblock %}

<!-- User Panel -->
{% block panel %}
    <div class="card-slots">
        <!-- Use javascript to insert card here -->
        {% for user in interests %}
            <div class="card display-user" data-selected-id="{{ user.id }}">
                <img src="{{ user.picture }}" alt="matches-pic" data-interest-pic="{{ user.picture }}" id="card-slot-pic">
                <div class="card-body">
                    <p><a href="#" class="matches-name" id="interest-name">{{ user.full_name }}</a></p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

<!-- Display Panel -->
{% block display %}
    <div class="user-container random-users" id="random-user" data-random-id="{{ match.userid }}">
        <img class="users-img" id="random-user-img" src="{{ match.picture }}" alt="user-picture">
        <div class="random-user-info">
            <h5 id="random-user-fullname">{{ match.fullname }}</h5>
            <p id="random-user-age">{{ match.age }}</p>
        </div>
        <div class="bottom-buttons">
            <i class="fa-solid fa-arrow-right fa-2xl" style="color: #ef4f4f;" id="next-btn"></i>
            <i class="fa-solid fa-heart fa-bounce fa-2xl" style="color: #ff0000;" id="interested"></i>
            <i class="fa-solid fa-xmark fa-2xl" style="color: #FEBE48;" id="not-interested"></i>
        </div>
    </div>
     <!-- Selected User Modal-->
     <div class="modal fade" id="selectedUserModal" tabindex="-1" role="dialog" aria-labelledby="selectedUserModalLabel" aria-hidden="true">
        <div class="modal-dialog selectDialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="selected-user-container">
                        <img id="selected-user-img" class="users-img" src="" alt="user-picture">
                        <div class="selected-user-info">
                            <h5 id="selected-user-fullname"></h5>
                            <p id="selected-age"></p>
                            <p id="selected-city"></p>, <p id="selected-state"></p>
                        </div>
                        <button id="sendMessageOnSelect"><i class="fa-regular fa-message fa-lg"></i>Send Message</button>
                        <p onclick="moreInfo()" style="cursor: pointer;">more info</p>
                        <div class="more-info" style="display: none; padding: 0; height: 100%;">
                            <ul style="list-style: none; color: black;">
                                <li id="li-more-info">School: <p id="selected-school"></p></li>
                                <li id="li-more-info">Company: <p id="selected-company"></p></li>
                            </ul>
                        </div>
                    </div>  
                </div>
            </div>
        </div>
    </div>
                  

{% endblock %}

myapp/templates/messages.html
{% extends "index.html" %}

{% block title %}
    Messages
{% endblock %}

{% block panel %}
    {% for user in participants %}
    <div class="conversation-slot" data-user-id="{{ user.id }}">
        <img src="{{ user.picture }}" alt="" class="card-pic">
        <div class="card-info">
            <h5>{{user.full_name}}</h5>
            <p class="senderMessage"></p>
        </div>
    </div>
    {% endfor %}

    {% if not participants %}
    <div class="no-messages-default">
        <i class="fa-solid fa-envelope-open-text fa-2xl" style="color: #ef4f4f;"></i>
    </div>
        
    {% endif %}
{% endblock %}

{% block display %}     
      <!-- Modal -->
    <div class="modal fade" id="chatWindowModal" tabindex="-1" role="dialog" aria-labelledby="chatWindowModal" aria-hidden="true">
        <div class="modal-dialog messageDialog" role="document">
            <div class="modal-content message">
                <div class="message-container" id="chat-window">
                    <div class="message-info">
                        <div class="closeChatWindow">x</div>
                        <img id="user-message-img" src="" alt="user-message">
                        <h5 id="user-message-name"></h5>
                    </div>
                    <div class="message-area" id="output">
                        <!-- Javscript messages -->
                    </div>
                    <div class="input-container">
                        <textarea id="messageInput" placeholder="Type a message"></textarea>
                        <!-- Send Button -->
                        <i class="fa-solid fa-paper-plane fa-2xl" style="color: #ef4848; cursor: pointer;" id="sendButton"></i>
                    </div> 
                </div>
            </div>
        </div>
    </div>
{% endblock %}